### ISSUE TITLE
EDT

### ISSUE THREAD

**Issue by carlos-chrs** [SistemasTecTlaxiaco/actividad-7-estructura-de-desglose-de-trabajo-edt-entrevista-gestion-de-proyectos#1]
[Practica 6 EDT.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-estructura-de-desglose-de-trabajo-edt-entrevista-gestion-de-proyectos/files/9880606/Practica.6.EDT.pdf)

**Comment by IsraelNicolas61** [comment]
20/20
¡Buen trabajo!

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
